version: '1'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:5.7.16
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-${DB_ROOT_PASWORD}}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD:-${DB_ROOT_PASWORD}}
      MYSQL_USER: ${MYSQL_USER:-admin}
    volumes:
      - database_data:/var/lib/mysql
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data: 
###< doctrine/doctrine-bundle ###
